### ISSUE TITLE
MS Dynamics NAV

### ISSUE THREAD

**Issue by vbrh-immalle** [JorenDR-immalle/StageVerslagen#1]
Kan je hier eens kort uitleggen waarvoor men daar MS Dynamics NAV gebruikt en welke modules (als het zo genoemd wordt?) vooral van belang zijn?

**Comment by JorenDR-immalle** [comment]
Beste,

VanRoey Automation gebruikt MS Dynamics NAV voor bijna alles, men maakt
hier de bonnen mee, het wordt gebruikt als ticketsysteem,
openboekhoudprogramma, facturen worden hiermee opgesteld, bestellingen en
reparaties worden doorgegeven en het wordt ook gebruikt als een compacte
database. Bijna 90% van hun modules zijn zelf geschreven code. Door deze
zelfgemaakte modules vereenvoudigd dit het werk zodat alles via dit
programma in deze sector bereikbaar is.

Hopelijk verduidelijkt deze mail het gebruik van dit programma in deze
sector.

Met vriendelijke groeten,
Joren De Rijk

Op ma 30 sep. 2019 om 20:32 schreef Hans Van Broeckhoven <
notifications@github.com>:

**Comment by vbrh-immalle** [comment]
Leuk dat je deze issue via mail hebt doorgestuurd naar GitHub. Je hoeft issues echter niet als een echte mail te beschouwen (dus de groeten zijn niet nodig ;-).

**Comment by vbrh-immalle** [comment]
Bekijk zeker ook de issues eens online op github.com
